;; (if (string-equal system-type "windows-nt")
;;     (defconst my-emacs-path "c:/gitbox/dot_emacs/")
(defconst my-emacs-path (file-truename "~/.emacs.d/"))

(defconst my-lisps-path  (concat my-emacs-path "mylisps/") "Path for self lisps")
(defconst their-lisps-path  (concat my-emacs-path "theirlisps/") "Path for others' lisps")
(defconst my-templates-path (concat my-emacs-path "templates/") "Path for templates")

;; load all my-lisps 
(load (concat my-lisps-path "my-subdirs"))
(my-add-subdirs-to-load-path my-lisps-path)
(my-add-subdirs-to-load-path their-lisps-path)

(require 'basic-setting)
(require 'keybind-setting)
(require 'helpfunc-setting)
(require 'plugin-setting)
(require 'orgmode-setting)
(require 'ibuffer-setting)
(require 'path-setting)
(require 'font-setting)
(require 'python-setting)
(require 'yasnippet-setting)
(require 'w3m-setting)
(require 'shell-setting)
(require 'slime-setting)
(require 'cc-setting)
(require 'javascript-setting)
(require 'modeline-setting)
(require 'colortheme-setting)

(byte-recompile-directory "." 0)
